config/routes.rb
Rails.application.routes.draw do
  get 'home', to: 'restaurants#home'
  resources :restaurants do
    resources :reviews, only: [:create]
  end
end
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/restaurant.rb
class Restaurant < ApplicationRecord
  validates :name, presence: true
  validates :address, presence: true
  validates :category, presence: true, inclusion: { in: %w(chinese italian japanese french belgian), message: "%{value} is not a valid category"}

  has_many :reviews, dependent: :destroy
  validates_associated :reviews
end

app/models/review.rb
class Review < ApplicationRecord
  belongs_to :restaurant

  validates :content, presence: true
  validates :rating, presence: true
  validates_numericality_of :rating, only_integer: true
  validates_inclusion_of :rating, { in: (0..5) }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/restaurants_controller.rb
class RestaurantsController < ApplicationController
  before_action :find_restaurant, only: [:show, :edit, :update, :destroy]



  def index

    @restaurants = Restaurant.all
  end

  def show
    @review = Review.new
  end

  def new
    @restaurant = Restaurant.new
  end

  def edit
  end

  def create
    @restaurant = Restaurant.new(restaurant_params)
    if @restaurant.save
      redirect_to @restaurant, notice: 'Restaurant was successfully created.'
    else
      render :new
    end
  end

  def update
    if @restaurant.update(restaurant_params)
      redirect_to @restaurant, notice: 'Restaurant was successfully updated.'
    else
      render :edit
    end
  end

  def destroy
    @restaurant.destroy
    redirect_to restaurants_url, notice: 'Restaurant was successfully destroyed.'
  end
  def home
    @date = Date.today.strftime("%A, %b %d")
  end

  private

  def find_restaurant
    @restaurant = Restaurant.find(params[:id])
  end

  def restaurant_params
    params.require(:restaurant).permit(:name, :address, :phone_number, :category)
  end
end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController
  before_action :find_restaurant

  def create
    @review = Review.new(review_params)
    @review.restaurant = @restaurant
    if @review.save
      redirect_to restaurant_path(@restaurant)
    else
      render :new
    end
  end

  private

  def find_restaurant
    @restaurant = Restaurant.find(params[:restaurant_id])
  end

  def review_params
    params.require(:review).permit(:content, :rating)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/restaurants_helper.rb
module RestaurantsHelper
end

app/helpers/reviews_helper.rb
module ReviewsHelper
end

app/views/layouts/_footer.html.erb
<!-- Footer -->
<footer class="page-footer font-small black pt-4">

  <!-- Footer Links -->
  <div class="container-fluid text-center text-md-left">

    <!-- Grid row -->
    <div class="row">

      <!-- Grid column -->
      <div class="col-md-6 mt-md-0 mt-3">

        <!-- Content -->
        <h5 class="text-uppercase">Footer Content</h5>
        <p>Here you can use rows and columns to organize your footer content.</p>

      </div>
      <!-- Grid column -->

      <hr class="clearfix w-100 d-md-none pb-3">

      <!-- Grid column -->
      <div class="col-md-3 mb-md-0 mb-3">

        <!-- Links -->
        <h5 class="text-uppercase">Home</h5>



      </div>
      <!-- Grid column -->

      <!-- Grid column -->

      <!-- Grid column -->

    </div>
    <!-- Grid row -->

  </div>
  <!-- Footer Links -->

  <!-- Copyright -->
  <div class="footer-copyright text-center py-3">© 2020 Copyright:
    <a href="https://mdbootstrap.com/"> MDBootstrap.com</a>
  </div>
  <!-- Copyright -->

</footer>
<!-- Footer -->

app/views/layouts/_navbar.html.erb
<nav class="navbar navbar-expand-lg navbar-light bg-light">
  <a class="navbar-brand" href="#">Restaurants Review</a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>
  <div class="collapse navbar-collapse" id="navbarNav">
    <ul class="navbar-nav">
      <li class="nav-item active">
        <a class="nav-link" href="#"> Home <span class="sr-only">(current)</span></a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="#">Create a Restaurant</a>
      </li>

    </ul>
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsYelpMvp</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
   <%= render '/layouts/navbar' %>
    <%= yield %>

  </body>
</html>

app/views/restaurants/_form.html.erb
<%= simple_form_for(@restaurant) do |f| %>
  <%= f.error_notification %>
  <%= f.error_notification message: f.object.errors[:base].to_sentence if f.object.errors[:base].present? %>

  <div class="form-inputs">
    <%= f.input :name %>
    <%= f.input :address %>
    <%= f.input :category%>
  </div>

  <div class="form-actions btn btn-primary">
    <%= f.button :submit %>
  </div>
<% end %>

app/views/restaurants/_navbar.html.erb
<nav class="navbar navbar-expand-lg navbar-light bg-light">
  <a class="navbar-brand" href="#">Restaurant</a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>
  <div class="collapse navbar-collapse" id="navbarNav">
    <ul class="navbar-nav">
      <li class="nav-item active">
        <%= link_to 'Our Restaurants', restaurants_path, class: "nav-link" %> <span class="sr-only">(current)</span>
      </li>
      <li class="nav-item">
       <%= link_to "Create a Restaurant", new_restaurant_path, class: "nav-link" %>
      </li>
    </ul>
  </div>
</nav>

app/views/restaurants/edit.html.erb
<div class="container mt-5">
  <h1>Editing Restaurant</h1>

  <%= render 'form', restaurant: @restaurant %>

  <%= link_to 'Show', @restaurant %> |
  <%= link_to 'Back', restaurants_path %>

</div>

app/views/restaurants/home.html.erb
<div class="container mt-5">
  <h1>Welcome to Reviu |</h1>
 <p> Go crazy. Reviu it ALL!</p>


  <%= link_to 'List all restaurants', restaurants_path %>


</div>

app/views/restaurants/index.html.erb
<div class="container main-container mt-5">

<h1> Restaurants List</h1>
<div> <% @restaurants.each do |restaurant| %>

    <p><%= link_to restaurant.name, restaurant_path(restaurant) %></p>
    <p> Address : <%= restaurant.address %> </p>
    <p> Category : <%= restaurant.category %> </p>
    <%= link_to 'Edit', edit_restaurant_path(restaurant), class: "btn btn-primary" %>
          <% end %>

  </div>
<%= link_to 'Add a new Restaurant', new_restaurant_path, class: "btn btn-primary" %>

app/views/restaurants/new.html.erb
<div class="container mt-5">
  <h1>Add new Restaurant</h1>

  <%= render 'form', restaurant: @restaurant %>

  <%= link_to 'Back', restaurants_path %>

</div>

app/views/restaurants/show.html.erb
<div class="container mt-5">
  <p id="notice"><%= notice %></p>
  <h1>
    <strong><%= @restaurant.name %></strong>
  </h1>
  <p>
    <strong>Address:</strong>
    <%= @restaurant.address %>
  </p>
  <p>
    <strong>Category:</strong>
    <%= @restaurant.category %>
  </p>
  <%= link_to 'Edit', edit_restaurant_path(@restaurant) %>
  <hr>

  <p>
    <strong>Reviews:</strong>
  </p>
  <% @restaurant.reviews.each do |review| %>
  <p><%= review.content %></p>
  <p> <%= "Rating  #{'*' * review.rating}" %> </p>

  <% end %>

</div>


<div class="container mt-5">

  <h1>Add a review for <%= @restaurant.name %></h1>
  <%= simple_form_for [@restaurant, @review] do |f| %>
  <div class="form-inputs">
  <%= f.input :content %>
  <%= f.input :rating %>
</div>
<div class="form-actions btn btn-primary">
  <%= f.button :submit %>
</div>


<%= link_to 'Back to all Restaurants', restaurants_path %>
</div>
<% end %>